name: Translate
main: Awzaw\Translate\Main
version: 1.0.1
api: [2.0.0, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
author: Awzaw
website: "http://jdcraft.net"
load: POSTWORLD
commands:
  translate:
    usage: "/translate"
    aliases: [tra]
    description: "Turn on translation"
    permission: translate
permissions:
  translate:
    default: true
    description: "Allows access to Translation"