name: Translate
main: Awzaw\Translate\Main
version: 1.0.3-1
api: [3.0.0]
author: Awzaw
website: "http://jdcraft.net"
load: POSTWORLD
commands:
  translate:
    usage: "/translate"
    aliases: [tra]
    description: "Turn on translation"
    permission: translate
permissions:
  translate:
    default: true
    description: "Allows access to Translation"